version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run: docker build -t compmem/meld:$CIRCLE_BUILD_NUM-${CIRCLE_SHA1:0:6} .

      - run: docker push compmem/meld
    